# workflow.yml
id: 59e886be-3295-492e-a62a-ef37e9ec6137
workflow: Master Planning: Exception Resolution Workflow
model: Master Planning

steps:
  - name: Review Exceptions
    type: action
    description: ""
  - name: Check with Plant Scheduler for Additional Capacity
    type: action
    description: ""
  - name: Collaborate with Material Planner for Material Shortage
    type: action
    description: ""
  - name: Resolve Material Exception
    type: action
    description: ""
  - name: Update Master Planner
    type: action
    description: ""
  - name: Review Revised Plan
    type: action
    description: ""
  - name: Compare and Merge to Base Scenario
    type: action
    description: ""
  - name: Override Production Plan
    type: action
    description: ""
  - name: Approve Production Plan
    type: action
    description: ""